/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as MinisplitsRouteImport } from './routes/minisplits'
import { Route as RefaccionesRouteImport } from './routes/refacciones'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisplitsRoute = MinisplitsRouteImport.update({
  id: '/minisplits',
  path: '/minisplits',
  getParentRoute: () => rootRouteImport,
} as any)
const RefaccionesRoute = RefaccionesRouteImport.update({
  id: '/refacciones',
  path: '/refacciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/herramientas': typeof HerramientasRoute
  '/minisplits': typeof MinisplitsRoute
  '/refacciones': typeof RefaccionesRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/herramientas': typeof HerramientasRoute
  '/minisplits': typeof MinisplitsRoute
  '/refacciones': typeof RefaccionesRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/herramientas': typeof HerramientasRoute
  '/minisplits': typeof MinisplitsRoute
  '/refacciones': typeof RefaccionesRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/herramientas'
    | '/minisplits'
    | '/refacciones'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/herramientas'
    | '/minisplits'
    | '/refacciones'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/herramientas'
    | '/minisplits'
    | '/refacciones'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  HerramientasRoute: typeof HerramientasRoute
  MinisplitsRoute: typeof MinisplitsRoute
  RefaccionesRoute: typeof RefaccionesRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minisplits': {
      id: '/minisplits'
      path: '/minisplits'
      fullPath: '/minisplits'
      preLoaderRoute: typeof MinisplitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refacciones': {
      id: '/refacciones'
      path: '/refacciones'
      fullPath: '/refacciones'
      preLoaderRoute: typeof RefaccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  HerramientasRoute: HerramientasRoute,
  MinisplitsRoute: MinisplitsRoute,
  RefaccionesRoute: RefaccionesRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
